### PR TITLE
First pass at dev environments guide

### PR DESCRIPTION
**Pull request by adelevie**

### CODE REVIEW

**Comment by cmc333333** [comment]
The content here makes sense. Happy to merge as is but I'll make two suggestions:

1. Would this make sense in the https://github.com/18F/dev-environment-standardization repo (there's also https://github.com/18F/dev-environment, but it's been dead for a while)? The documentation working group hasn't quite figured out how to merge all these repos yet, so figuring out where to put things is a bit up in the air.
1. I think your core message is about simplifying travis scripts to reduce duplication between environments, but that message is a bit muddied by the more grandiose introduction on the page. I don't think we need to re-iterate why documentation, etc. are important; removing those pieces might focus the message more.

**Comment by adelevie** [comment]
Good suggestions! I wasn't even aware of those two other repos. And only learned about the dev guide repo last week and wanted to add to it.

Re #2, that's a good idea. Maybe re-focus into `.travis.yml` good/best practices?

I can see why we don't need more words spent on why documentation etc is good. I started writing this as a Docker-for-dev-environments guide, but first wanted to write some generic principles, hence this PR. I wanted to tee up some basic parts before writing something that ties them together (e.g. Docker/docker-compose for local dev env, then Docker/docker-compose on Travis, and finally, how to use the experimental Docker stuff on Cloud.gov (something I still need to learn).

I'd like to work on some Docker guidance/how-tos next, and want _something_ to cite back to as to why. Whether that's the thing I put together, or a different doc, is fine by me.

Also, maybe I'll open a new issue in https://github.com/18F/dev-environment-standardization for this, but (when) should we push harder that every repo use Docker/docker-compose for setup?

**Comment by cmc333333** [comment]
Agreed; I didn't mean to imply this was the _wrong_ place -- I'm just not sure it's the right place :)

Merging this as is and we can trim it down if desired.

**Comment by adelevie** [comment]
I'm not wrong, @cmc333333! :)

**Pull request merged**
