### PR TITLE
Adds CircleCi examples for testing and deploying.

### LINKED ISSUE #86: update references to TravisCI
https://github.com/18F/development-guide/tree/master/continuous_deployment

### PR DESCRIPTION
**Pull request by ondrae**
This PR adds CircleCI example code for testing and deploying to Cloud.gov. ~~It's using the [CloudFoundry Orb](https://circleci.com/orbs/registry/orb/circleci/cloudfoundry) to hide most of the boilerplate code, just requiring the needed config variables.~~

The included example will run tests on all branches. The Cloud.gov deploy will only happen when the tests pass on the master branch.

~~I've included links in the comments to the documentation in case people want to implement blue green deploys.~~

Closes #86

### CODE REVIEW

**Comment by ondrae** [comment]
I spent some time trying out the recommended Autopilot plugin and it is not supported anymore. The repo itself is [archived and unmaintained](https://github.com/contraband/autopilot), and the latest versions of the Cloud Foundry CLI [no longer give plugins the needed access](https://github.com/cloudfoundry/cli/blob/master/plugin/plugin_examples/README.md#known-issues).

I'd recommend instead we start using blue green deploys. https://docs.cloudfoundry.org/devguide/deploy-apps/blue-green.html

I'm new here though and don't have any good projects here to use as examples.

**Comment by afeld** [comment]
Autopilot is doing those blue-green deployments for you. The future is using the built-in [rolling deployments](https://docs.cloudfoundry.org/devguide/deploy-apps/rolling-deploy.html), but not sure how far that is from stable. Not sure what it makes sense to recommend before then.

**Comment by ryanhofdotgov** [comment]
I actually stopped using autopilot a while back for my prototypes on cloud.gov because it would break about once a month (2-3 deploys a day). I had to delete `venerable` instances manually (see https://github.com/contraband/autopilot/issues/37).

cloud.gov's [production ready guidance](https://cloud.gov/docs/apps/production-ready/) still lists autopilot, but also zdt with a caution about it potentially changing. Anecdotally, I've seen a handful of folks on TTS Slack switch to `v3-zdt-push` successfully. Nicest thing about this built-in zdt is that it doesn't require twice the space quota as your baseline to do the blue-green deployment.

I think for the purposes of this dev guide, in absence of a clear winner, it would be OK to lay out the tradeoffs and let the reader choose a solution.

**Comment by ondrae** [comment]
Reverts to using the autopilot plugin in the example, for consistency. At the end is a list of zero downtime deploy options.

What do you think?

**Comment by ryanhofdotgov** [comment]
@ondrae These look like good changes 👍, but I was confused about the tie to #86, which just says "update references to Travis CI". Didn't see any Travis references changed in the changeset (but also don't know what the original intent of #86 is). Would you clarify – thanks!

**Comment by ondrae** [comment]
Aiden had asked me to update the docs to add CircleCI in a Slack conversation at https://gsa-tts.slack.com/archives/C02CD5VUQ/p1567107649012300?thread_ts=1567097422.009900&cid=C02CD5VUQ.

He may have meant to also remove the Travis references, I'm just new so I don't know if people still use it or not. Do they? Should I take out all the Travis stuff?

**Comment by ryanhofdotgov** [comment]
@ondrae Sorry for the long delay – I've been swamped with end of fiscal year project work.

**Comment by ondrae** [comment]
No problem, I was about to check on the status.

I still have the question of if I should also remove all the Travis examples. Do people still use it for projects here? Is it still allowed to be used?

**Comment by ryanhofdotgov** [comment]
Ah, yes – you are correct @ondrae. Here's a quick PR for you to review https://github.com/18F/development-guide/pull/88

**Pull request merged**
