### PR TITLE
Add suggestion to use Allstar to enforce consistency across repos

### PR DESCRIPTION
**Pull request by markdboyd**

### CODE REVIEW

**Comment by svenaas** [comment]
This looks good to me. @Sgtpluck, you've done a fair bit of work in this file. Would you like to review as well?

**Review by Sgtpluck — APPROVED** [review]
I think it looks good! Is it possible to add a link to where cloud.gov is using it, @markdboyd? That would be very nice to have!

**Comment by markdboyd** [comment]
@Sgtpluck How about 58e6ee4d26f2d3d82561a3dcb266e147879d77d9?

**Comment by Sgtpluck** [comment]
@markdboyd perfect!!! thank you.

**Comment by Sgtpluck** [comment]
The pa11y failure is fine as per https://github.com/actions/first-interaction/issues/10#issuecomment-545576314 -- it's because the PR is coming from a fork.

**Comment by markdboyd** [comment]
@Sgtpluck OK, thanks! I don't have access to merge PRs on this repo, so someone else will have to merge for me

**Review by kbighorse — APPROVED** [review]
👍🏾

**Pull request merged**
