### PR TITLE
Add development environment document

### PR DESCRIPTION
**Pull request by jessieay**

### CODE REVIEW

**Comment by jessieay** [comment]
cc @kaitlin :)

**Comment by monfresh** [comment]
The content looks great to me. When I first saw the title of this PR, I thought it was going to talk about the machine setup. That's what I usually associate "development environment" with. The guidelines discussed here might better be placed under a different topic, such as "Project Setup" perhaps? What do you think?

"Setting up the Development Environment" to me means something like running the laptop script and using Vagrant or Docker.

**Comment by monfresh** [comment]
Another thing that might be worth adding is a section about using Git pre-commit hooks, as @arowla mentioned here: https://docs.google.com/document/d/11zjcaSJmJewivsrtHcY5RHIfcUOn9BtWlNC7Ofz1U5w/edit

**Comment by kaitlin** [comment]
Yeah I agree with @monfresh. Maybe something like "Starting a New Project" would be better?

**Comment by jessieay** [comment]
@monfresh @kaitlin Thanks for taking a look. Renamed to "project setup" -- I liked the explicitness of "starting a new project" but there are definitely some existing projects that aren't using these sets of tools yet, so I wanted to make sure we didn't scope this doc to be for future projects only.

@monfresh re: git pre-commit hooks -- which ones exactly did you have in mind? Might make sense to merge this and then add to it. Or, if you want to drop a comment with something to add explicitly, I will happily add. This doc so far is just based on my exposure to 18F practices and I am not using any pre-commit hooks at the moment.

**Comment by monfresh** [comment]
Let's merge for now and add the pre-commit hooks later. I haven't used them here either, but I know other projects do, namely midas. I think @ultrasaurus is a fan.

**Comment by arowla** [comment]
@jmcarp is a big fan of the pre-commit hooks, too.

**Comment by jmcarp** [comment]
Join the pre-commit club here: http://pre-commit.com/hooks.html

**Pull request merged**
