### PR TITLE
Merge content under (JavaScript, CSS) directories into single pages

### PR DESCRIPTION
**Pull request by Sgtpluck**
Addresses #199.

* Uses `include_relative` to avoid having to actually cop/paste everything in.
* Cleaned up a couple things in the JavaScript docs but didn't go too wild about it as these pages need more ❤️ than is in scope.
* Added a list of topics at the top to make the pages more navigable -- curious if there should also be some anchor links that toggle back up to the top under each topic.

### CODE REVIEW

**Comment by ryanhofdotgov** [comment]
Cool! A couple of quick thoughts:
* Unfortunately, the `include_relative` paradigm breaks the "Edit this page" model that's part of most TTS handbooks. Try out the corresponding, bottom right link that should be on every engineering practices guide page to see how that workflow goes.
* There's a built-in uswds-jekyll mechanism for intra-page subsections that could replace (or augment) your top level links. Checkout the [Code Review page for an example](https://engineering.18f.gov/code-review/).

**Comment by Sgtpluck** [comment]
@ryanhofdotgov this look better? thanks for the review!

**Comment by Sgtpluck** [comment]
whew that's one way to get some user feedback @ryanhofdotgov! thanks for the tip, that's really smart.

**Review by ryanhofdotgov — APPROVED** [review]
Nice!

**Pull request merged**
