### PR TITLE
Update JS framework page

### LINKED ISSUE #133: Update classifications on the JavaScript framework page
See the [survey results](https://gsa-tts.slack.com/archives/C02CD5VUQ/p1584110150091700) from #dev channel, and update/remove React, Angular, etc. sections on the [JavaScript framework page](https://engineering.18f.gov/javascript/frameworks/), in accordance with the consensus.

### PR DESCRIPTION
**Pull request by mgwalker**
Makes a first pass at updating the JS frameworks page

- adds a new `Caution` tag
- adds some text at the top about also considering vanilla JS
- makes React our default
- makes Angular a suggestion, updates language to reflect Angular rather than AngularJS
- adds a "deprecated" section and puts AngularJS, Backbone, and jQuery in it
  - @cantsin @hbillings ☝️ Since y'all chimed in about Backbone and jQuery, would y'all like to take a pass at some words about why we discourage those?

Will eventually close #133

### CODE REVIEW

**Comment by cantsin** [comment]
Had this on my todo list for awhile, finally getting around to this! My 2c:

- Backbone and its associated libraries (such as Marionette) are generally in maintenance mode only. Backbone is ostensibly finished (and thus stable) but any bug fixes or improvements to this framework are likely not going to happen. From what I can see, the Backbone community has dwindled and several associated projects have languished. It would be a hard sell to use Backbone for any new projects going forward. For these reasons I believe we should deprecate Backbone. 

- jQuery is a library, not a framework, so I'm not sure if it belongs here. jQuery's raison d'etre (papering over interoperability issues) has been largely diminished today but I believe there are still many other frameworks using it (Bootstrap for instance). For new development, especially front-end apps that target modern browsers, there's much less of a reason to use jQuery, imo. But ultimately it doesn't really matter if a framework uses jQuery, I wouldn't use that as a reason to reject or deprecate a framework.

(Wanted to start a discussion and come to some agreement before pushing content to this PR)

**Comment by mgwalker** [comment]
That is great and exactly what I was hoping for. If we're going to deprecate something, it's good to be able to say why.

I like your point about jQuery too. So maybe we say something like don't use jQuery yourself, but don't disqualify a framework that uses it under the hood?

**Comment by cantsin** [comment]
Re: jQuery, absolutely agree. What's the next step: do you want me to push up some wording to this PR or...?

**Comment by ryanhofdotgov** [comment]
Just an editorial thought – these library/framework type pages could become dominated by deprecated entries as technology marches on. 

In the spirit of "less is more", I might lean towards documenting many/most of the deprecation reasons in the change history/issues, and keeping the content focused.

**Comment by mgwalker** [comment]
@ryanhofdotgov That makes sense. Maybe we can just list them as they age-out, keep them for a little while, and then drop them altogether? In that case, I'm not sure we need to talk about either Backbone or jQuery, since they both aged-out a while ago?

(I would encourage us to keep the Angular.js entry for now, as a distinction from Angular, though it's probably pretty close to old enough that I could be persuaded otherwise.)

**Comment by ryanhofdotgov** [comment]
@mgwalker For sure – whatever you feel is best as far as what meets the threshold. Thanks!

**Comment by ryanhofdotgov** [comment]
@mgwalker Mind if I edit out the in-progress sections on Backbone/JQuery and merge? I think what you've up so far is valuable and want to get it published on the site.

**Comment by mgwalker** [comment]
Go for it!

**Pull request merged**
